import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
import { origin, outputPath, httpCredentials } from './config.mjs';
import { installAssessment } from './assessment-fixtures.mjs';

const browser = await chromium.launch(), label = process.argv[2] ?? 'candidate';
const out = { label, checks: [], errors: [] }, cleanups = [];
const destination = page => JSON.parse(new URL(page.url()).searchParams.get('destination'));
async function open(page, keyboard = false) {
  await page.getByRole('button', { name: 'Search workspace', exact: true }).waitFor();
  if (keyboard) await page.keyboard.press('Control+Shift+P');
  else await page.getByRole('button', { name: 'Search workspace', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('combobox', { name: 'Search everything…', exact: true }).waitFor();
  await dialog.locator('[data-modal-motion]').evaluate(async node => {
    node.getBoundingClientRect();
    await Promise.all(node.getAnimations().map(animation => animation.finished.catch(() => {})));
  });
  assert.equal(await dialog.getByRole('tab', { name: 'All', exact: true }).getAttribute('aria-selected'), 'true');
  return dialog;
}
try {
  for (const motion of ['no-preference', 'reduce']) {
    const context = await browser.newContext({ httpCredentials, reducedMotion: motion, colorScheme: 'dark', viewport: { width: 1440, height: 1000 } });
    const fixture = await installAssessment(context, { profileId: 'am' }); cleanups.push(fixture.cleanup);
    const page = await context.newPage(); page.on('pageerror', error => out.errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error' && /unique.*key|same key/.test(message.text())) out.errors.push(message.text()); });
    await page.goto(origin + '/?destination=' + encodeURIComponent(JSON.stringify({ version: 1, owner: 'am', surface: null, target: { projectId: null, worktreeId: null, orgId: 'uat' } })));
    let dialog = await open(page, true);
    const input = () => dialog.getByRole('combobox', { name: 'Search everything…', exact: true });
    const rows = () => dialog.getByRole('listbox').getByRole('option');
    assert.equal(await dialog.getByLabel('Resource org', { exact: true }).count(), 0);
    const orgPill = () => dialog.getByRole('button', { name: 'Browse orgs, resource org: UAT Sandbox', exact: true });
    assert.equal(await orgPill().innerText(), 'UAT Sandbox');
    assert.equal(await dialog.getByRole('button', { name: 'Clear search', exact: true }).count(), 0);
    const ids = await rows().evaluateAll(nodes => nodes.map(node => node.id));
    assert.equal(new Set(ids).size, ids.length, 'Mixed worktree/session identities must be unique');
    await input().fill('Account');
    const beforeControls = page.url();
    await dialog.getByRole('button', { name: 'Clear search', exact: true }).click();
    assert.equal(await input().inputValue(), '');
    assert(await input().evaluate(node => node === document.activeElement));
    assert.equal(await rows().count(), ids.length);
    await input().fill('Account');
    await orgPill().focus(); await page.keyboard.press('Enter');
    const orgInput = dialog.getByRole('combobox', { name: 'Search orgs…', exact: true });
    assert.equal(await dialog.getByRole('tab', { name: 'Orgs', exact: true }).getAttribute('aria-selected'), 'true');
    assert.equal(await orgInput.inputValue(), '', 'Org pill shows choices instead of retaining an unrelated resource search');
    assert(await orgInput.evaluate(node => node === document.activeElement));
    assert(await rows().filter({ hasText: 'UAT Sandbox' }).isVisible());
    assert.equal(page.url(), beforeControls, 'Pill and clear only change palette state');
    for (const [tab, query] of [['Surfaces', 'Code'], ['Projects', 'Trailblazer'], ['Sessions', 'lead routing'], ['Orgs', 'UAT']]) {
      await dialog.getByRole('tab', { name: tab, exact: true }).click();
      const search = dialog.getByRole('combobox', { name: `Search ${tab.toLowerCase()}…`, exact: true });
      await search.fill(query);
      const clear = dialog.getByRole('button', { name: 'Clear search', exact: true });
      await clear.focus(); await clear.press('Enter');
      assert.equal(await search.inputValue(), '');
      assert.equal(await dialog.getByRole('tab', { name: tab, exact: true }).getAttribute('aria-selected'), 'true');
      assert(await search.evaluate(node => node === document.activeElement));
    }
    assert.equal(page.url(), beforeControls);
    out.checks.push(`${motion}: org pill opens Orgs with visible choices without navigating; clear search retains All/category and returns focus`);
    await dialog.getByRole('tab', { name: 'All', exact: true }).click();
    await input().fill('Account');
    assert((await rows().first().innerText()).includes('Standard object · Account · UAT Sandbox'));
    await page.screenshot({ path: outputPath(`${label}-all-search-${motion}.png`) });
    await input().press('Enter'); await dialog.waitFor({ state: 'detached' });
    await page.getByRole('article', { name: 'Account resource', exact: true }).waitFor();
    assert.deepEqual(destination(page).target, { projectId: null, worktreeId: null, orgId: 'uat' });
    out.checks.push(`${motion}: shortcut defaults to All; exact Account precedes partial names; resource opens its canvas while staying global`);

    dialog = await open(page); await input().fill('lead routing');
    const text = await rows().allTextContents();
    const parent = text.findIndex(row => row.startsWith('Trailblazer CRM'));
    assert(parent >= 0 && text[parent + 1].includes('Worktree · feature/lead-routing'), 'Ranked worktree stays connected to its project');
    assert(text.some(row => row.includes('Session · Trailblazer CRM')));
    assert(text.some(row => row.includes('Flow · Lead_Routing · UAT Sandbox')));
    const highlighted = rows().filter({ has: page.locator('[class*="resultLabel"]', { hasText: /^lead-routing$/ }) });
    assert.equal(await highlighted.filter({ hasText: 'Worktree ·' }).getAttribute('aria-selected'), 'true');
    await input().press('Enter'); await dialog.waitFor({ state: 'detached' });
    await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.worktreeId === 'lead-routing');
    assert.equal(destination(page).target.projectId, 'trailblazer-crm');
    assert.equal(destination(page).target.worktreeId, 'lead-routing');
    out.checks.push(`${motion}: matching project, worktree, session and flow are distinguishable; Enter chooses the matched worktree with its tree intact`);

    dialog = await open(page); await input().fill('Account'); await input().press('Enter');
    await dialog.waitFor({ state: 'detached' });
    await page.getByRole('article', { name: 'Account resource', exact: true }).waitFor();
    assert.equal(destination(page).target.projectId, 'trailblazer-crm');
    assert.equal(destination(page).target.worktreeId, 'lead-routing');
    dialog = await open(page); await input().fill('Code');
    await dialog.getByRole('button', { name: /^Code Surface ·/ }).click();
    await dialog.waitFor({ state: 'detached' }); await page.waitForURL(url => url.pathname === '/code');
    assert.equal(destination(page).target.worktreeId, 'lead-routing');
    out.checks.push(`${motion}: resource and surface selections preserve the active project/worktree`);

    await page.getByRole('link', { name: 'Global home', exact: true }).click();
    await page.waitForURL(url => url.pathname === '/');
    dialog = await open(page); await input().fill('Acme Storefront');
    await rows().filter({ hasText: 'Project · main' }).getByRole('button').click();
    await dialog.waitFor({ state: 'detached' });
    await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.projectId === 'acme-storefront');
    assert.equal(destination(page).target.projectId, 'acme-storefront');
    dialog = await open(page); await input().fill('lead routing');
    await rows().filter({ hasText: 'Session · Trailblazer CRM · feature/lead-routing' }).getByRole('button').click();
    await dialog.waitFor({ state: 'detached' });
    await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.worktreeId === 'lead-routing');
    assert.equal(destination(page).target.projectId, 'trailblazer-crm');
    assert.equal(destination(page).target.worktreeId, 'lead-routing');
    dialog = await open(page); await input().fill('Production');
    await rows().filter({ hasText: 'Org · Production · Connected' }).getByRole('button').click();
    await dialog.waitFor({ state: 'detached' });
    await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.orgId === 'prod');
    assert.deepEqual(destination(page).target, { projectId: 'trailblazer-crm', worktreeId: 'lead-routing', orgId: 'prod' });
    out.checks.push(`${motion}: explicit project/session results enter their context; org results change only the org`);

    dialog = await open(page); await input().fill('Release_Checklist__c');
    assert.equal(await rows().count(), 0);
    await dialog.getByRole('tab', { name: 'Resources', exact: true }).click();
    await dialog.getByLabel('Resource org', { exact: true }).selectOption('uat');
    assert.equal(await rows().count(), 1);
    assert.equal(destination(page).target.orgId, 'prod', 'Choosing a search filter must not navigate');
    const resourceInput = dialog.getByRole('combobox', { name: 'Search resources…', exact: true });
    assert.equal(await resourceInput.inputValue(), 'Release_Checklist__c');
    await dialog.getByLabel('Resource type', { exact: true }).selectOption('flow');
    assert.equal(await rows().count(), 0);
    await dialog.getByRole('button', { name: 'Clear search', exact: true }).click();
    assert.equal(await resourceInput.inputValue(), '');
    assert(await resourceInput.evaluate(node => node === document.activeElement));
    assert.equal(await dialog.getByLabel('Resource org', { exact: true }).inputValue(), 'uat');
    assert.equal(await dialog.getByLabel('Resource type', { exact: true }).inputValue(), 'flow');
    assert(await rows().count() > 0, 'Clearing a resource query restores results within the current filters');
    await resourceInput.fill('Release_Checklist__c');
    await dialog.getByRole('tab', { name: 'All', exact: true }).click();
    assert(await orgPill().isVisible(), 'All pill reflects the actual resource inventory selected in Resources');
    assert.equal(await rows().count(), 1, 'All is not restricted by a resource-type filter');
    await input().press('Enter'); await dialog.waitFor({ state: 'detached' });
    await page.getByRole('article', { name: 'Release Checklist resource', exact: true }).waitFor();
    assert.deepEqual(destination(page).target, { projectId: 'trailblazer-crm', worktreeId: 'lead-routing', orgId: 'uat' });
    dialog = await open(page); await input().fill('nothing-matches-this-identifier');
    assert.equal(await rows().count(), 0);
    await input().press('Enter'); assert(await dialog.isVisible());
    await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'detached' });
    assert(fixture.commands.every(command => command.kind === 'visit'));
    out.checks.push(`${motion}: Resources filters change inventory without navigation; clear retains org/type; All pill reflects inventory and ignores resource-type filtering; no-match Enter is harmless`);
    await context.close();
  }
  const context = await browser.newContext({ httpCredentials, reducedMotion: 'reduce', colorScheme: 'light', viewport: { width: 390, height: 844 } });
  const fixture = await installAssessment(context, { profileId: 'sp' }); cleanups.push(fixture.cleanup);
  const page = await context.newPage(); page.on('pageerror', error => out.errors.push(error.message));
  await page.goto(origin + '/');
  const dialog = await open(page);
  const input = dialog.getByRole('combobox', { name: 'Search everything…', exact: true });
  await dialog.getByText('Choose an org to include its resources.', { exact: false }).waitFor();
  await input.fill('Account'); assert.equal(await dialog.getByRole('listbox').getByRole('option').count(), 0);
  await dialog.getByRole('button', { name: 'Choose an org', exact: true }).click();
  await dialog.getByRole('listbox').getByRole('option').filter({ hasText: 'UAT Sandbox' }).getByRole('button').click();
  await dialog.waitFor({ state: 'detached' });
  await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.orgId === 'uat');
  await open(page);
  assert(await dialog.getByRole('button', { name: 'Browse orgs, resource org: UAT Sandbox', exact: true }).isVisible());
  await input.fill('LeadRoutingService'); assert.equal(await dialog.getByRole('listbox').getByRole('option').count(), 0);
  await input.fill('Code'); assert.equal(await dialog.getByRole('button', { name: /^Code Surface ·/ }).count(), 0);
  await input.fill('Account');
  assert((await dialog.getByRole('listbox').getByRole('option').first().innerText()).includes('Standard object · Account · UAT Sandbox'));
  assert(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth));
  await page.screenshot({ path: outputPath(`${label}-all-search-mobile.png`) });
  await input.press('Enter'); await dialog.waitFor({ state: 'detached' });
  await page.getByRole('article', { name: 'Account resource', exact: true }).waitFor();
  assert.equal(destination(page).target.projectId, null);
  out.checks.push('No-org state explains resource scope; narrow light layout and restricted-profile resource/surface access are preserved');
  await context.close();
} catch (error) { out.errors.push(error.stack); }
finally {
  await browser.close(); cleanups.forEach(cleanup => cleanup());
  writeFileSync(outputPath(`${label}-unified-search.json`), JSON.stringify(out, null, 2));
  console.log(JSON.stringify(out, null, 2)); if (out.errors.length) process.exitCode = 1;
}
