import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
import { origin, outputPath, httpCredentials } from './config.mjs';
import { installAssessment } from './assessment-fixtures.mjs';

const browser = await chromium.launch(), label = process.argv[2] ?? 'candidate';
const out = { label, checks: [], errors: [] }, cleanups = [];
const destination = page => JSON.parse(new URL(page.url()).searchParams.get('destination'));
async function open(page, keyboard = false) {
  await page.getByRole('button', { name: 'Search workspace', exact: true }).waitFor();
  if (keyboard) await page.keyboard.press('Control+Shift+P');
  else await page.getByRole('button', { name: 'Search workspace', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('combobox', { name: 'Search everything…', exact: true }).waitFor();
  await dialog.locator('[data-modal-motion]').evaluate(async node => {
    node.getBoundingClientRect();
    await Promise.all(node.getAnimations().map(animation => animation.finished.catch(() => {})));
  });
  assert.equal(await dialog.getByRole('tab', { name: 'All', exact: true }).getAttribute('aria-selected'), 'true');
  return dialog;
}
try {
  for (const motion of ['no-preference', 'reduce']) {
    const context = await browser.newContext({ httpCredentials, reducedMotion: motion, colorScheme: 'dark', viewport: { width: 1440, height: 1000 } });
    const fixture = await installAssessment(context, { profileId: 'am' }); cleanups.push(fixture.cleanup);
    const page = await context.newPage(); page.on('pageerror', error => out.errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error' && /unique.*key|same key/.test(message.text())) out.errors.push(message.text()); });
    await page.goto(origin + '/?destination=' + encodeURIComponent(JSON.stringify({ version: 1, owner: 'am', surface: null, target: { projectId: null, worktreeId: null, orgId: 'uat' } })));
    let dialog = await open(page, true);
    const input = () => dialog.getByRole('combobox', { name: 'Search everything…', exact: true });
    const rows = () => dialog.getByRole('listbox').getByRole('option');
    assert.equal(await dialog.getByLabel('Resource org', { exact: true }).count(), 0);
    const orgPill = () => dialog.getByRole('button', { name: 'Browse orgs, resource org: UAT Sandbox', exact: true });
    assert.equal(await orgPill().innerText(), 'UAT Sandbox');
    assert.equal(await dialog.getByRole('button', { name: 'Clear search', exact: true }).count(), 0);
    const ids = await rows().evaluateAll(nodes => nodes.map(node => node.id));
    assert.equal(new Set(ids).size, ids.length, 'Mixed worktree/session identities must be unique');
    const categories = ids.map(id => id.split(':')[0].replace('cmd-all-', ''));
    assert.deepEqual(categories.filter((category, index) => category !== categories[index - 1]),
      ['projects', 'resources', 'sessions', 'orgs', 'surfaces'], 'All prioritizes files before sessions and navigation');
    assert.equal(await rows().first().getAttribute('aria-selected'), 'true', 'All starts at the top instead of scrolling to the current org/surface');
    await input().fill('Account');
    const beforeControls = page.url();
    await dialog.getByRole('button', { name: 'Clear search', exact: true }).click();
    assert.equal(await input().inputValue(), '');
    assert(await input().evaluate(node => node === document.activeElement));
    assert.equal(await rows().count(), ids.length);
    await input().fill('Account');
    await orgPill().focus(); await page.keyboard.press('Enter');
    const orgInput = dialog.getByRole('combobox', { name: 'Search orgs…', exact: true });
    assert.equal(await dialog.getByRole('tab', { name: 'Orgs', exact: true }).getAttribute('aria-selected'), 'true');
    assert.equal(await orgInput.inputValue(), '', 'Org pill shows choices instead of retaining an unrelated resource search');
    assert(await orgInput.evaluate(node => node === document.activeElement));
    assert(await rows().filter({ hasText: 'UAT Sandbox' }).isVisible());
    assert.equal(page.url(), beforeControls, 'Pill and clear only change palette state');
    for (const [tab, query] of [['Surfaces', 'Code'], ['Projects', 'Trailblazer'], ['Sessions', 'lead routing'], ['Orgs', 'UAT']]) {
      await dialog.getByRole('tab', { name: tab, exact: true }).click();
      const search = dialog.getByRole('combobox', { name: `Search ${tab.toLowerCase()}…`, exact: true });
      await search.fill(query);
      const clear = dialog.getByRole('button', { name: 'Clear search', exact: true });
      await clear.focus(); await clear.press('Enter');
      assert.equal(await search.inputValue(), '');
      assert.equal(await dialog.getByRole('tab', { name: tab, exact: true }).getAttribute('aria-selected'), 'true');
      assert(await search.evaluate(node => node === document.activeElement));
    }
    assert.equal(page.url(), beforeControls);
    out.checks.push(`${motion}: org pill opens Orgs with visible choices without navigating; clear search retains All/category and returns focus`);
    await dialog.getByRole('tab', { name: 'All', exact: true }).click();
    await input().fill('Account');
    assert((await rows().first().innerText()).includes('Standard object · Account · UAT Sandbox'));
    await page.screenshot({ path: outputPath(`${label}-all-search-${motion}.png`) });
    await input().press('Enter'); await dialog.waitFor({ state: 'detached' });
    await page.getByRole('article', { name: 'Account resource', exact: true }).waitFor();
    assert.deepEqual(destination(page).target, { projectId: null, worktreeId: null, orgId: 'uat' });
    out.checks.push(`${motion}: shortcut defaults to All; exact Account precedes partial names; resource opens its canvas while staying global`);

    dialog = await open(page); await input().fill('lead routing');
    const text = await rows().allTextContents();
    const parent = text.findIndex(row => row.startsWith('Trailblazer CRM'));
    assert.equal(parent, 0, 'Project results remain first during search');
    assert(await rows().nth(parent).getByText('ALM', { exact: true }).isVisible(), 'All shows the project record as an ALM canvas');
    assert(text.findIndex(row => row.includes('Flow · Lead_Routing · UAT Sandbox'))
      < text.findIndex(row => row.includes('Session · Trailblazer CRM')), 'Resources precede sessions during search');
    assert(text.some(row => row.includes('Session · Trailblazer CRM')));
    assert(text.some(row => row.includes('Flow · Lead_Routing · UAT Sandbox')));
    await dialog.getByRole('tab', { name: 'Projects', exact: true }).click();
    const projectText = await rows().allTextContents();
    const projectParent = projectText.findIndex(row => row.startsWith('Trailblazer CRM'));
    assert(projectParent >= 0 && projectText[projectParent + 1].includes('feature/lead-routing'), 'Projects keeps worktrees attached to their parent');
    const highlighted = rows().filter({ has: page.locator('[class*="resultLabel"]', { hasText: /^lead-routing$/ }) });
    await highlighted.getByRole('button').focus(); await highlighted.getByRole('button').press('Enter'); await dialog.waitFor({ state: 'detached' });
    await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.worktreeId === 'lead-routing');
    assert.equal(destination(page).target.projectId, 'trailblazer-crm');
    assert.equal(destination(page).target.worktreeId, 'lead-routing');
    out.checks.push(`${motion}: All identifies project records by ALM; Projects retains keyboard worktree selection and intact project trees`);

    dialog = await open(page); await input().fill('Account'); await input().press('Enter');
    await dialog.waitFor({ state: 'detached' });
    await page.getByRole('article', { name: 'Account resource', exact: true }).waitFor();
    assert.equal(destination(page).target.projectId, 'trailblazer-crm');
    assert.equal(destination(page).target.worktreeId, 'lead-routing');
    dialog = await open(page); await input().fill('Code');
    await dialog.getByRole('button', { name: /^Code Surface ·/ }).click();
    await dialog.waitFor({ state: 'detached' }); await page.waitForURL(url => url.pathname === '/code');
    assert.equal(destination(page).target.worktreeId, 'lead-routing');
    out.checks.push(`${motion}: resource and surface selections preserve the active project/worktree`);

    dialog = await open(page); await input().fill('Trailblazer CRM');
    const projectFile = dialog.locator('[id="cmd-all-projects:trailblazer-crm"]');
    assert.equal(await projectFile.getByText('Current', { exact: true }).count(), 0);
    await projectFile.getByRole('button').click(); await dialog.waitFor({ state: 'detached' });
    await page.getByRole('heading', { name: 'Trailblazer CRM', exact: true }).waitFor();
    assert.equal(destination(page).surface, 'alm'); assert.equal(destination(page).target.worktreeId, 'lead-routing');
    assert.equal(destination(page).canvas.kind, 'improvement-project');

    await page.getByRole('link', { name: 'Global home', exact: true }).click();
    await page.waitForURL(url => url.pathname === '/');
    dialog = await open(page); await input().fill('Acme Storefront');
    await dialog.locator('[id="cmd-all-projects:acme-storefront"]').getByRole('button').click();
    await dialog.waitFor({ state: 'detached' });
    await page.getByRole('heading', { name: 'Acme Storefront', exact: true }).waitFor();
    assert.equal(destination(page).surface, 'alm'); assert.equal(destination(page).target.projectId, null);
    assert.equal(destination(page).canvas.params.projectId, 'acme-storefront');
    dialog = await open(page);
    await dialog.getByRole('tab', { name: 'Projects', exact: true }).click();
    await dialog.getByRole('combobox', { name: 'Search projects…', exact: true }).fill('Acme Storefront');
    await rows().filter({ has: page.getByText('Acme Storefront', { exact: true }) }).getByRole('button').click();
    await dialog.waitFor({ state: 'detached' });
    await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.projectId === 'acme-storefront');
    assert.equal(destination(page).target.projectId, 'acme-storefront');
    dialog = await open(page); await input().fill('lead routing');
    await rows().filter({ hasText: 'Session · Trailblazer CRM · feature/lead-routing' }).getByRole('button').click();
    await dialog.waitFor({ state: 'detached' });
    await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.worktreeId === 'lead-routing');
    assert.equal(destination(page).target.projectId, 'trailblazer-crm');
    assert.equal(destination(page).target.worktreeId, 'lead-routing');
    dialog = await open(page); await input().fill('Production');
    await rows().filter({ hasText: 'Org · Production · Connected' }).getByRole('button').click();
    await dialog.waitFor({ state: 'detached' });
    await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.orgId === 'prod');
    assert.deepEqual(destination(page).target, { projectId: 'trailblazer-crm', worktreeId: 'lead-routing', orgId: 'prod' });
    out.checks.push(`${motion}: All opens sample project canvases while retaining Home/worktrees; Projects/session selections enter context; org results change only the org`);

    dialog = await open(page); await input().fill('Release_Checklist__c');
    assert.equal(await rows().filter({ hasText: 'Release_Checklist__c' }).count(), 0, 'Production has no matching resource; other categories may match the query');
    await dialog.getByRole('tab', { name: 'Resources', exact: true }).click();
    await dialog.getByLabel('Resource org', { exact: true }).selectOption('uat');
    assert.equal(await rows().count(), 1);
    assert.equal(destination(page).target.orgId, 'prod', 'Choosing a search filter must not navigate');
    const resourceInput = dialog.getByRole('combobox', { name: 'Search resources…', exact: true });
    assert.equal(await resourceInput.inputValue(), 'Release_Checklist__c');
    await dialog.getByLabel('Resource type', { exact: true }).selectOption('flow');
    assert.equal(await rows().count(), 0);
    await dialog.getByRole('button', { name: 'Clear search', exact: true }).click();
    assert.equal(await resourceInput.inputValue(), '');
    assert(await resourceInput.evaluate(node => node === document.activeElement));
    assert.equal(await dialog.getByLabel('Resource org', { exact: true }).inputValue(), 'uat');
    assert.equal(await dialog.getByLabel('Resource type', { exact: true }).inputValue(), 'flow');
    assert(await rows().count() > 0, 'Clearing a resource query restores results within the current filters');
    await resourceInput.fill('Release_Checklist__c');
    await dialog.getByRole('tab', { name: 'All', exact: true }).click();
    assert(await orgPill().isVisible(), 'All pill reflects the actual resource inventory selected in Resources');
    assert.equal(await rows().filter({ hasText: 'Release_Checklist__c' }).count(), 1, 'All is not restricted by a resource-type filter');
    await input().press('Enter'); await dialog.waitFor({ state: 'detached' });
    await page.getByRole('article', { name: 'Release Checklist resource', exact: true }).waitFor();
    assert.deepEqual(destination(page).target, { projectId: 'trailblazer-crm', worktreeId: 'lead-routing', orgId: 'prod' });
    assert.equal(destination(page).canvas.params.orgId, 'uat', 'Inspecting a search result captures its org without switching the connection');
    dialog = await open(page); await input().fill('nothing-matches-this-identifier');
    assert.equal(await rows().count(), 0);
    await input().press('Enter'); assert(await dialog.isVisible());
    await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'detached' });
    assert(fixture.commands.every(command => command.kind === 'visit'));
    out.checks.push(`${motion}: Resources filters change inventory without navigation; clear retains org/type; All pill reflects inventory and ignores resource-type filtering; no-match Enter is harmless`);
    await context.close();
  }
  {
    const context = await browser.newContext({ httpCredentials, reducedMotion: 'reduce', colorScheme: 'dark', viewport: { width: 1440, height: 1000 } });
    const fixture = await installAssessment(context, { profileId: 'sp' }); cleanups.push(fixture.cleanup);
    const finding = fixture.run.findings[0];
    const project = { id: 'palette-plan', name: 'Acme org improvements', goal: 'Reduce unnecessary requests', owner: 'Sam Patel', targetOrgId: 'sit', scopeOrgIds: ['prod', 'sit'], createdAt: '2026-09-22T12:00:00Z', revision: 1, runId: fixture.run.id, sourceDraftId: 'palette-draft', createCommandId: 'palette-command', workItems: [{ id: 'WI-1', title: finding.title, priority: 'High', status: 'todo', findingId: finding.id, finding }] };
    fixture.state.snapshot.assessment.projects.push(project, { ...project, id: 'other-plan', name: 'Other project', source: 'brief', projectType: 'react', runId: null, workItems: [] });
    const page = await context.newPage(); page.on('pageerror', error => out.errors.push(error.message));
    const target = { projectId: project.id, worktreeId: null, orgId: 'uat' };
    await page.goto(origin + '/build?destination=' + encodeURIComponent(JSON.stringify({ version: 1, owner: 'sp', surface: 'build', target })));
    let dialog = await open(page);
    await dialog.getByRole('combobox').fill(project.name);
    const row = () => dialog.locator('[id="cmd-all-projects:palette-plan"]');
    assert.equal(await row().getByText('Current', { exact: true }).count(), 0);
    assert(await row().getByText('ALM', { exact: true }).isVisible());
    await page.screenshot({ path: outputPath(`${label}-project-alm-result.png`) });
    await dialog.getByRole('combobox').press('Enter'); await dialog.waitFor({ state: 'detached' });
    await page.getByRole('heading', { name: project.name, exact: true }).waitFor();
    await page.getByLabel(`Status for ${finding.title}`, { exact: true }).waitFor();
    assert.deepEqual(destination(page).target, target); assert.equal(destination(page).surface, 'alm');
    assert.equal(destination(page).canvas.params.projectId, project.id);
    dialog = await open(page); await dialog.getByRole('combobox').fill('Other project');
    assert.equal(await dialog.locator('[id="cmd-all-projects:other-plan"]').count(), 0, 'Project file results stay scoped inside a project');
    await dialog.getByRole('tab', { name: 'Projects', exact: true }).click();
    assert(await dialog.getByRole('listbox').getByRole('option').filter({ hasText: 'Other project' }).isVisible(), 'Projects remains a global workspace selector');
    await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'detached' });
    await page.getByRole('link', { name: 'Global home', exact: true }).click(); await page.waitForURL(url => url.pathname === '/');
    dialog = await open(page); await dialog.getByRole('combobox').fill(project.name);
    await row().getByRole('button').click(); await dialog.waitFor({ state: 'detached' });
    await page.getByRole('heading', { name: project.name, exact: true }).waitFor();
    assert.deepEqual(destination(page).target, { projectId: null, worktreeId: null, orgId: 'uat' });
    assert.equal(destination(page).canvas.params.projectId, project.id);
    await page.reload(); await page.getByRole('heading', { name: project.name, exact: true }).waitFor();
    assert.equal(destination(page).target.projectId, null);
    dialog = await open(page); await dialog.getByRole('tab', { name: 'Projects', exact: true }).click();
    await dialog.getByRole('combobox').fill(project.name);
    await dialog.getByRole('listbox').getByRole('option').filter({ hasText: project.name }).getByRole('button').click();
    await dialog.waitFor({ state: 'detached' });
    await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.projectId === project.id);
    dialog = await open(page); await dialog.getByRole('combobox').fill(project.name);
    assert.equal(await row().getByText('Current', { exact: true }).count(), 0, 'Even the active project canvas keeps its ALM destination label');
    assert(await row().getByText('ALM', { exact: true }).isVisible());
    assert(fixture.commands.every(command => command.kind === 'visit'));
    out.checks.push('Created project records show ALM instead of Current, open their saved work-item canvas, retain scoped/global context and reload, and keep explicit switching in Projects');
    await context.close();
  }
  const context = await browser.newContext({ httpCredentials, reducedMotion: 'reduce', colorScheme: 'light', viewport: { width: 390, height: 844 } });
  const fixture = await installAssessment(context, { profileId: 'sp' }); cleanups.push(fixture.cleanup);
  const page = await context.newPage(); page.on('pageerror', error => out.errors.push(error.message));
  // Exercise the supported no-org destination explicitly; ordinary sign-in now selects an org.
  await page.goto(origin + '/?destination=' + encodeURIComponent(JSON.stringify({ version: 1, owner: 'sp', surface: null,
    target: { projectId: null, worktreeId: null, orgId: null } })));
  const dialog = await open(page);
  const input = dialog.getByRole('combobox', { name: 'Search everything…', exact: true });
  await dialog.getByText('Choose an org to include its resources.', { exact: false }).waitFor();
  await input.fill('Account'); assert.equal(await dialog.getByRole('listbox').getByRole('option').count(), 0);
  await dialog.getByRole('button', { name: 'Choose an org', exact: true }).click();
  await dialog.getByRole('listbox').getByRole('option').filter({ hasText: 'UAT Sandbox' }).getByRole('button').click();
  await dialog.waitFor({ state: 'detached' });
  await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.orgId === 'uat');
  await open(page);
  assert(await dialog.getByRole('button', { name: 'Browse orgs, resource org: UAT Sandbox', exact: true }).isVisible());
  await input.fill('LeadRoutingService'); assert.equal(await dialog.getByRole('listbox').getByRole('option').count(), 0);
  await input.fill('Code'); assert.equal(await dialog.getByRole('button', { name: /^Code Surface ·/ }).count(), 0);
  await input.fill('Account');
  assert((await dialog.getByRole('listbox').getByRole('option').first().innerText()).includes('Standard object · Account · UAT Sandbox'));
  assert(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth));
  await page.screenshot({ path: outputPath(`${label}-all-search-mobile.png`) });
  await input.press('Enter'); await dialog.waitFor({ state: 'detached' });
  await page.getByRole('article', { name: 'Account resource', exact: true }).waitFor();
  assert.equal(destination(page).target.projectId, null);
  out.checks.push('No-org state explains resource scope; narrow light layout and restricted-profile resource/surface access are preserved');
  await context.close();
} catch (error) { out.errors.push(error.stack); }
finally {
  await browser.close(); cleanups.forEach(cleanup => cleanup());
  writeFileSync(outputPath(`${label}-unified-search.json`), JSON.stringify(out, null, 2));
  console.log(JSON.stringify(out, null, 2)); if (out.errors.length) process.exitCode = 1;
}
