import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
import { origin, outputPath, httpCredentials } from './config.mjs';
import { installAssessment } from './assessment-fixtures.mjs';
import { testModules } from '../test-modules.mjs';
const modules = testModules(), { destinationHref } = modules.load('lib/navigation/model');
const browser = await chromium.launch(), label = process.argv[2] ?? 'candidate';
const out = { label, checks: [], errors: [] }, cleanups = [];
const current = page => JSON.parse(new URL(page.url()).searchParams.get('destination'));
async function checkCenteredSearch(page) {
  for (const width of [1920, 1440, 1280, 1024, 800, 390]) {
    await page.setViewportSize({ width, height: 1000 });
    const search = await page.getByRole('button', { name: 'Search workspace', exact: true }).boundingBox();
    assert(Math.abs(search.x + search.width / 2 - width / 2) < 1, `Search is viewport-centered at ${width}px`);
    const trigger = page.getByRole('button', { name: /^Changes, / });
    if (await trigger.count()) {
      const changes = await trigger.boundingBox();
      assert(changes.y + changes.height <= search.y || changes.x + changes.width <= search.x, `Changes do not overlap search at ${width}px`);
    }
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `Header fits at ${width}px`);
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
}
try {
  const context = await browser.newContext({ httpCredentials, colorScheme: 'dark', reducedMotion: 'reduce', viewport: { width: 1440, height: 1000 } });
  const fixture = await installAssessment(context, { profileId: 'sp' }); cleanups.push(fixture.cleanup);
  const page = await context.newPage(); page.on('pageerror', error => out.errors.push(error.message));
  const global = { projectId: null, worktreeId: null, orgId: 'uat' };
  await page.goto(origin + destinationHref({ version: 1, owner: 'sp', surface: null, target: global }));
  await page.getByRole('group', { name: 'Today', exact: true }).waitFor();
  await checkCenteredSearch(page);
  const trigger = page.getByRole('button', { name: /^Changes, / });
  const popover = page.getByRole('dialog', { name: 'Changes', exact: true });
  assert.equal(await trigger.count(), 0, 'Global Home hides the indicator when there are no changes');
  assert.equal(await popover.count(), 0);
  const panel = page.locator('#workspace-panel');
  if (await panel.getAttribute('data-open') !== 'true') await page.locator('#workspace-panel-toggle').click();
  await panel.getByRole('button', { name: 'Start project', exact: true }).click();
  await page.getByLabel('Project name', { exact: true }).fill('Sam’s service project');
  await page.getByLabel('What should this project achieve?', { exact: true }).fill('Reduce manual handoffs');
  await page.getByRole('button', { name: 'Create project', exact: true }).click();
  await page.getByRole('heading', { name: 'Sam’s service project', exact: true }).waitFor();
  const project = fixture.state.snapshot.assessment.projects[0];
  await page.getByRole('button', { name: 'Changes, 2 changed files', exact: true }).waitFor();
  const switcher = page.getByRole('banner').getByRole('button', { name: /^Switch project, / });
  const [projectBox, changeBox] = await Promise.all([switcher.boundingBox(), trigger.boundingBox()]);
  assert(changeBox.x >= projectBox.x + projectBox.width, 'Changes sit to the right of the project selector');
  await checkCenteredSearch(page);
  await trigger.focus(); await trigger.press('Enter');
  await popover.waitFor();
  await page.keyboard.press('Escape'); assert(await trigger.evaluate(el => el === document.activeElement));
  await trigger.press('Enter');
  assert.equal(await popover.getByRole('button', { name: /^Open changed file / }).count(), 2);
  assert.equal(await popover.getByRole('button', { name: 'Track in a project', exact: true }).count(), 0);
  assert.equal(await popover.getByLabel('Added', { exact: true }).count(), 2);
  await page.screenshot({ path: outputPath(`${label}-project-changes-dark.png`) });
  await popover.getByRole('button', { name: 'Open changed file .project/project.json', exact: true }).click();
  await page.getByRole('article', { name: 'project.json file', exact: true }).waitFor();
  assert.equal(current(page).target.projectId, project.id);
  const definition = JSON.parse(await page.getByLabel('File contents', { exact: true }).textContent());
  assert.equal(definition.goal, 'Reduce manual handoffs');
  await trigger.click();
  await popover.getByRole('button', { name: 'Open changed file .project/work-items.json', exact: true }).click();
  await page.getByRole('article', { name: 'work-items.json file', exact: true }).waitFor();
  await page.reload(); await page.getByRole('button', { name: 'Changes, 2 changed files', exact: true }).waitFor(); await trigger.click();
  assert.equal(await popover.getByRole('button', { name: /^Open changed file / }).count(), 2);
  await page.setViewportSize({ width: 390, height: 844 }); await page.emulateMedia({ colorScheme: 'light' });
  const box = await popover.boundingBox(); assert(box.x >= 0 && box.x + box.width <= 390);
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await page.screenshot({ path: outputPath(`${label}-project-changes-narrow.png`) });
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('link', { name: 'Global home', exact: true }).click();
  await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.projectId === null);
  await trigger.waitFor({ state: 'detached' });
  out.checks.push('Sam creates a project: two added context files, scoped opening/reload, right-of-selector placement, no project tracking CTA, keyboard and narrow/light/dark layout');

  const canvas = { kind: 'capability', title: 'Build an automation', params: { scope: 'unbound', surface: 'build', capability: 'automation', orgId: 'uat' } };
  await page.goto(origin + destinationHref({ version: 1, owner: 'sp', surface: 'build', target: global, canvas }));
  const name = page.getByLabel('Name', { exact: true });
  await name.waitFor();
  assert.equal(await trigger.count(), 0, 'Merely opening a global draft does not show changes');
  await name.fill('Lead routing');
  await page.getByRole('button', { name: 'Changes, 1 changed file', exact: true }).waitFor();
  await name.fill('');
  await trigger.waitFor({ state: 'detached' });
  await name.fill('Lead routing');
  await page.getByLabel('What would you like to build?', { exact: true }).fill('Route leads to the right team');
  await page.getByRole('button', { name: 'Changes, 1 changed file', exact: true }).waitFor();
  await page.getByRole('link', { name: 'Global home', exact: true }).click();
  await page.getByRole('button', { name: 'Changes, 1 changed file', exact: true }).waitFor();
  out.checks.push('Global indicator stays hidden at zero, appears after the first edit, hides when edits are cleared, and shows existing changes on return to Home');
  await trigger.click();
  await popover.getByRole('button', { name: 'Open changed file .drafts/uat/build/automation.json', exact: true }).click();
  await name.waitFor(); assert.equal(await name.inputValue(), 'Lead routing'); assert.equal(current(page).target.projectId, null);
  await trigger.click(); await popover.getByRole('button', { name: 'Track in a project', exact: true }).click();
  await popover.getByRole('button', { name: 'Create a new project', exact: true }).waitFor();
  assert.equal(await popover.getByRole('combobox').count(), 0);
  assert.equal(await popover.getByRole('button', { name: 'Transfer changes', exact: true }).count(), 0);
  await popover.getByRole('button', { name: 'Use an existing project', exact: true }).click();
  assert.equal(await popover.getByRole('button', { name: 'Transfer changes', exact: true }).count(), 0);
  await popover.getByLabel('Choose a project', { exact: true }).selectOption(project.id);
  await page.screenshot({ path: outputPath(`${label}-global-track-changes.png`) });
  await popover.getByRole('button', { name: 'Transfer changes', exact: true }).click();
  await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.projectId === project.id);
  const transfer = fixture.commands.find(command => command.kind === 'changes.transfer');
  assert.equal(transfer.projectId, project.id);
  const source = fixture.state.snapshot.canvases.find(item => item.id === transfer.sources[0].sourceId);
  assert.deepEqual(source.fields, {});
  await page.getByRole('button', { name: 'Changes, 3 changed files', exact: true }).waitFor();
  assert.equal(await name.inputValue(), 'Lead routing');
  await page.getByRole('link', { name: 'Global home', exact: true }).click();
  await page.waitForURL(url => JSON.parse(url.searchParams.get('destination')).target.projectId === null);
  await trigger.waitFor({ state: 'detached' });
  await page.reload(); await page.getByRole('group', { name: 'Today', exact: true }).waitFor();
  assert.equal(await trigger.count(), 0, 'Transferred changes stay out of global Home after reload');
  await page.goto(origin + destinationHref({ version: 1, owner: 'sp', surface: 'build', target: global, canvas }));
  await name.waitFor(); assert.equal(await name.inputValue(), '', 'Global editor no longer contains the transferred draft');
  await name.fill('A separate global edit');
  await trigger.click(); await popover.getByRole('button', { name: 'Track in a project', exact: true }).click();
  await popover.getByRole('button', { name: 'Use an existing project', exact: true }).click();
  await popover.getByLabel('Choose a project', { exact: true }).selectOption(project.id);
  await popover.getByRole('button', { name: 'Transfer changes', exact: true }).click();
  await popover.getByRole('alert').waitFor();
  assert.equal(fixture.commands.filter(command => command.kind === 'changes.transfer').length, 1, 'Existing project draft is not overwritten');
  assert.equal(source.fields.name, 'A separate global edit', 'Rejected transfer preserves the global change');
  await page.getByRole('button', { name: 'Search workspace', exact: true }).click();
  assert.equal(await popover.count(), 0, 'Outside click closes changes');
  assert(fixture.commands.every(command => command.kind !== 'submit'), 'Reviewing/tracking does not invoke model work');
  out.checks.push('Create-new primary action; existing-project picker reveals transfer only after selection; successful transfer enters project and clears global/editor through reload; collisions preserve both files');
  await context.close();
  assert.deepEqual(out.errors, []);
} finally {
  writeFileSync(outputPath(`${label}-workspace-changes.json`), JSON.stringify(out, null, 2));
  await browser.close(); cleanups.forEach(cleanup => cleanup()); modules.cleanup();
}
console.log(JSON.stringify(out, null, 2));
